server.port=9090
spring.application.name=java-production-support-AI-agent

#Google Gemini API Key
spring.ai.google.genai.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.chat.model=gemini-3.6-flash

logging.level.org.springframework.ai=DEBUG

production.log.path=F:/CDP-microservices-demo/order-service/order-service/log/application.log